# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 22:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('display_name', models.CharField(max_length=30)),
                ('icon', models.CharField(max_length=30)),
                ('class_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StorageAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField()),
                ('status', models.IntegerField()),
                ('credentials', models.TextField(blank=True)),
                ('user_full_name', models.TextField()),
                ('user_short_name', models.TextField()),
                ('email', models.TextField()),
                ('display_name', models.TextField()),
                ('color', models.CharField(max_length=8)),
                ('cloud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigbox.CloudInterface')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
