# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 21:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudInterface',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=30)),
                ('icon', models.ImageField(upload_to='')),
                ('class_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StorageAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('refresh_token', models.TextField()),
                ('refresh_token_expire', models.DateTimeField()),
                ('access_token', models.TextField()),
                ('access_token_expire', models.DateTimeField()),
                ('additional_data', models.TextField()),
                ('cloud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigbox.CloudInterface')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
