# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudinterface',
            name='icon',
            field=models.CharField(max_length=30),
        ),
    ]
