# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigbox', '0002_auto_20170303_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageaccount',
            name='identifier',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
