# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 23:21
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bigbox', '0003_auto_20170419_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareditem',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='owner',
                                    to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
