# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigbox', '0003_storageaccount_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudinterface',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cloudinterface',
            name='name',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='storageaccount',
            name='access_token',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='storageaccount',
            name='additional_data',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='storageaccount',
            name='refresh_token',
            field=models.TextField(blank=True),
        ),
    ]
