# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bigbox', '0004_shareditem_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareditem',
            name='basedir',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
