# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 01:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigbox', '0004_auto_20170303_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageaccount',
            name='access_token_expire',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999)),
        ),
        migrations.AlterField(
            model_name='storageaccount',
            name='refresh_token_expire',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999)),
        ),
    ]
