# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigbox', '0005_auto_20170303_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageaccount',
            name='access_token_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storageaccount',
            name='refresh_token_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
